### ISSUE TITLE
out-of-date?

### ISSUE THREAD

**Issue by steenzout** [requests/requests-docs-pt#4]
I just read the English version and these docs seem for an older version.

do you need help keep the docs up-to-date?

**Comment by caizixian** [comment]
Yes, of course.

Keep the doc repo up-to-date is a great idea. Don't forget to keep existing translation though.

Thank you.

**Comment by steenzout** [comment]
@caizixian how do you manage this?

I'm guessing this is a fork of the main repo, correct?
if I do a `git pull` it will show up several merge conflicts.
is this what you want?

**Comment by caizixian** [comment]
IMHO, this is a legitimate way to get this done. Some of the conflicts need manual intervention though.
